@startuml

title __FRAMEWORK's Component Diagram__\n

  component "ds2os" {
        [light-adaptation-service]
        [sound-adaptation-service]
        [orchestration-service]
        [localization-service]
        [abstract-service]
        [bootstrap]
  }


  component "verifier" {
        [verifier-contract]
        [verifier-client]
        [verifier-common]
        [verifier-server]
  }


  component "orchestrator" {
        [orchestrator-contract]
        [orchestrator-client]
        [orchestrator-common]
        [orchestrator-server]
  }


  component "long_term_ca" {
        [long_term_ca-contract]
        [long_term_ca-client]
        [long_term_ca-common]
        [long_term_ca-server]
  }


  [abstract-service] --> [common]
  [bootstrap] --> [abstract-service]
  [bootstrap] --> [arduino]
  [bootstrap] --> [common]
  [bootstrap] --> [light-adaptation-service]
  [bootstrap] --> [sound-adaptation-service]
  [light-adaptation-service] --> [abstract-service]
  [light-adaptation-service] --> [arduino]
  [light-adaptation-service] --> [common]
  [localization-service] --> [abstract-service]
  [localization-service] --> [common]
  [long_term_ca-client] --> [common]
  [long_term_ca-client] --> [long_term_ca-common]
  [long_term_ca-client] --> [long_term_ca-contract]
  [long_term_ca-common] --> [common]
  [long_term_ca-contract] --> [common]
  [long_term_ca-contract] --> [long_term_ca-common]
  [long_term_ca-server] --> [common]
  [long_term_ca-server] --> [long_term_ca-common]
  [long_term_ca-server] --> [long_term_ca-contract]
  [orchestration-service] --> [abstract-service]
  [orchestration-service] --> [common]
  [orchestrator-client] --> [common]
  [orchestrator-client] --> [orchestrator-common]
  [orchestrator-client] --> [orchestrator-contract]
  [orchestrator-common] --> [common]
  [orchestrator-contract] --> [common]
  [orchestrator-contract] --> [orchestrator-common]
  [orchestrator-server] --> [abstract-service]
  [orchestrator-server] --> [common]
  [orchestrator-server] --> [long_term_ca-client]
  [orchestrator-server] --> [long_term_ca-common]
  [orchestrator-server] --> [long_term_ca-contract]
  [orchestrator-server] --> [orchestration-service]
  [orchestrator-server] --> [orchestrator-common]
  [orchestrator-server] --> [orchestrator-contract]
  [orchestrator-server] --> [verifier-client]
  [orchestrator-server] --> [verifier-common]
  [orchestrator-server] --> [verifier-contract]
  [sound-adaptation-service] --> [abstract-service]
  [sound-adaptation-service] --> [arduino]
  [sound-adaptation-service] --> [common]
  [verifier-client] --> [common]
  [verifier-client] --> [verifier-common]
  [verifier-client] --> [verifier-contract]
  [verifier-common] --> [common]
  [verifier-contract] --> [common]
  [verifier-contract] --> [verifier-common]
  [verifier-server] --> [common]
  [verifier-server] --> [long_term_ca-client]
  [verifier-server] --> [long_term_ca-common]
  [verifier-server] --> [long_term_ca-contract]
  [verifier-server] --> [orchestrator-client]
  [verifier-server] --> [orchestrator-common]
  [verifier-server] --> [orchestrator-contract]
  [verifier-server] --> [verifier-common]
  [verifier-server] --> [verifier-contract]


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
