@startuml

title __MATLAB's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace matlab {
      class pt.ulisboa.tecnico.surespace.verifier.matlab.LocationProofView {
          - beacons : LinkedHashSet<Beacon>
          - trustedSignals : LinkedHashSet<Signal>
          - untrustedSignals : LinkedHashSet<Signal>
          + LocationProofView()
          + getAuthorization()
          + getBeacons()
          + getTrustedSignals()
          + getUntrustedSignals()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace matlab {
      class pt.ulisboa.tecnico.surespace.verifier.matlab.SignalProcessing {
          - engine : MatlabProxy
          + SignalProcessing()
          + proofAccepted()
          - getAudioSimilarity()
          - getLightSimilarity()
          - getSimilarity()
          - process()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace matlab {
      class pt.ulisboa.tecnico.surespace.verifier.matlab.Wrapper {
          {static} - DATASET_PATH : String
          - engine : MatlabProxy
          + Wrapper()
          + close()
          + locationProofInit()
          + locationProofVerify()
          + locationProofWriteToDirectory()
          - assertNonNullLocationProof()
          - createDatasetsDir()
          - createProofDir()
          - getFile()
          - getFile()
          - getLocationProofDuration()
          - getLocationProofIdentifier()
          - writeFragmentToFile()
          - writeSignalToFile()
          - writeSignalsToFile()
          - writeToFile()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.verifier.matlab.LocationProofView o-- pt.ulisboa.tecnico.surespace.common.message.SignedRequestAuthorizationResponse : authorization
  pt.ulisboa.tecnico.surespace.verifier.matlab.Wrapper .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.verifier.matlab.Wrapper o-- pt.ulisboa.tecnico.surespace.verifier.matlab.LocationProofView : proofView
  pt.ulisboa.tecnico.surespace.verifier.matlab.Wrapper o-- pt.ulisboa.tecnico.surespace.verifier.matlab.SignalProcessing : signalProcessing


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
