@startuml

title __SERVICE's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    abstract class pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService {
        {static} # EXECUTORS : ExecutorService
        # fragmentCount : int
        # fragmentCurrent : int
        # fragmentLength : int
        - seed : long
        + AdaptationService()
        + close()
        {abstract} # beaconReset()
        {abstract} # beaconStart()
        {abstract} # beaconStop()
        # fragmentStart()
        # fragmentStop()
        # handleStart()
        # handleStop()
        # handleUnlock()
        # serviceBootstrap()
        {abstract} # serviceGenerateQuirkyProperties()
        # serviceLock()
        # servicePrepare()
        # serviceReset()
        # serviceStop()
        # serviceUnlock()
        # subscriptionsRegister()
        # subscriptionsUnregister()
        # utilFrequencyToPeriod()
        # utilPeriodToFrequency()
        - handleLock()
        - serviceBroadcast()
        - serviceStart()
        - serviceStartFragment()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.LockHandler {
        + lockExpired()
        + lockWillExpire()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    abstract class pt.ulisboa.tecnico.surespace.ds2os.service.Service {
        {static} # LOGGER : Logger
        # connector : ServiceConnector
        # nodeFactory : VslNodeFactory
        {static} - KEYSTORE_KEY : String
        + Service()
        + awaitForTermination()
        + close()
        + equals()
        + getKnowledgeRoot()
        + hashCode()
        # getAddress()
        # getNode()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    class pt.ulisboa.tecnico.surespace.ds2os.service.ServiceInitializer {
        - agentUrl : String
        - keyStore : String
        - serviceModelId : String
        + equals()
        + getAgentUrl()
        + getKeyStore()
        + getServiceModelId()
        + hashCode()
        + setAgentUrl()
        + setKeyStore()
        + setServiceModelId()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.SubscriberHandler {
        {abstract} + nodeChanged()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.VirtualNodeHandler {
        + get()
        + set()
    }
  }
  

  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.Service
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : beaconIsOn
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentCountNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentCurrentNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentLengthNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode : isLocked
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode : isStarted
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : seedNode
  pt.ulisboa.tecnico.surespace.ds2os.service.Service .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : agentRoot
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : knowledgeRoot
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.view.TypeSearchServiceView : searchService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
