@startuml

title __MANAGER's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorKeyStoreManager {
          + registerOrchestrator()
          # OrchestratorKeyStoreManager()
          # keyStoreInputStream()
          # keyStoreOutputStream()
          - entityManager()
          - getOrchestratorX500Name()
          - keyStoreFile()
          - managerLog()
          - managerProperty()
          - nonceManager()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorLogManager {
          - logger : Logger
          + OrchestratorLogManager()
          + debug()
          + error()
          + info()
          + warning()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager {
          + OrchestratorManager()
          + entity()
          + getVerifier()
          + getVerifierClient()
          + keyStore()
          + log()
          + nonce()
          + property()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorPropertyManager {
          + OrchestratorPropertyManager()
          + beforeLoading()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorKeyStoreManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.KeyStoreManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorKeyStoreManager o-- pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager : manager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorLogManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.LogManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager .up.|> pt.ulisboa.tecnico.surespace.common.manager.GlobalManagerInterface
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.common.manager.EntityManager : entityManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorKeyStoreManager : keyStoreManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorLogManager : logManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.common.manager.NonceManager : nonceManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorPropertyManager : propertyManager
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.common.domain.Entity : verifier
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager o-- pt.ulisboa.tecnico.surespace.verifier.client.VerifierClient : verifierClient
  pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorPropertyManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.PropertyManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
