@startuml

title __PIN's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace pin {
      class pt.ulisboa.tecnico.surespace.arduino.pin.AnalogArduinoPin {
          - analogPin : AnalogPin
          + AnalogArduinoPin()
          + write()
          # getPin()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace pin {
      abstract class pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin {
          {static} # LOGGER : Logger
          {static} # MAX_RETRIES : int
          {static} # TIMEOUT : int
          {static} # link : Link
          {static} - BAUD_RATE : int
          {static} - CUSTOM_PIN_MODE : String
          {static} - PIN_COUNTER : AtomicInteger
          - eventListeners : ConcurrentHashMap<Long, ArduinoPinListener>
          - pinId : int
          + ArduinoPin()
          + addListener()
          + close()
          + removeListener()
          + startListening()
          + stopListening()
          {abstract} # getPin()
          # getPinId()
          # sendCustomMessage()
          # setPinMode()
          - removeAllListeners()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace pin {
      enum PinMode {
        INPUT
        OUTPUT
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace pin {
      class pt.ulisboa.tecnico.surespace.arduino.pin.DigitalArduinoPin {
          - digitalPin : DigitalPin
          + DigitalArduinoPin()
          + write()
          # getPin()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.arduino.pin.AnalogArduinoPin -up-|> pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin
  pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin +-down- pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin.PinMode
  pt.ulisboa.tecnico.surespace.arduino.pin.DigitalArduinoPin -up-|> pt.ulisboa.tecnico.surespace.arduino.pin.ArduinoPin


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
