@startuml

title __LONG_TERM_CA-SERVER's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    class pt.ulisboa.tecnico.surespace.long_term_ca.LongTermCAApp {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    class pt.ulisboa.tecnico.surespace.long_term_ca.LongTermCAServiceImpl {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.long_term_ca.domain.LongTermCA {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace domain {
      namespace exception {
        class pt.ulisboa.tecnico.surespace.long_term_ca.domain.exception.LongTermCAException {
        }
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAKeyStoreManager {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCALogManager {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.long_term_ca {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAPropertyManager {
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.long_term_ca.LongTermCAServiceImpl -up-|> pt.ulisboa.tecnico.surespace.long_term_ca.grpc.LongTermCAServiceGrpc.LongTermCAServiceImplBase
  pt.ulisboa.tecnico.surespace.long_term_ca.LongTermCAServiceImpl o-- pt.ulisboa.tecnico.surespace.long_term_ca.domain.LongTermCA : longTermCA
  pt.ulisboa.tecnico.surespace.long_term_ca.domain.LongTermCA .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.long_term_ca.domain.LongTermCA o-- pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager : manager
  pt.ulisboa.tecnico.surespace.long_term_ca.domain.exception.LongTermCAException -up-|> pt.ulisboa.tecnico.surespace.common.exception.BroadException
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAKeyStoreManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.KeyStoreManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAKeyStoreManager o-- pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager : manager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCALogManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.LogManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager .up.|> pt.ulisboa.tecnico.surespace.common.manager.GlobalManagerInterface
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager o-- pt.ulisboa.tecnico.surespace.common.manager.EntityManager : entityManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager o-- pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAKeyStoreManager : keyStoreManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager o-- pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCALogManager : logManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager o-- pt.ulisboa.tecnico.surespace.common.manager.NonceManager : nonceManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAManager o-- pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAPropertyManager : propertyManager
  pt.ulisboa.tecnico.surespace.long_term_ca.manager.LongTermCAPropertyManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.PropertyManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
