@startuml

title __MANAGER's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.verifier.manager.VerifierKeyStoreManager {
          + registerVerifier()
          # VerifierKeyStoreManager()
          # keyStoreInputStream()
          # keyStoreOutputStream()
          - getVerifierX500Name()
          - keyStoreFile()
          - managerEntity()
          - managerLog()
          - managerProperty()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.verifier.manager.VerifierLogManager {
          - logger : Logger
          + VerifierLogManager()
          + debug()
          + error()
          + info()
          + warning()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager {
          + VerifierManager()
          + entity()
          + getOrchestrator()
          + getOrchestratorClient()
          + keyStore()
          + log()
          + nonce()
          + property()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.verifier {
    namespace manager {
      class pt.ulisboa.tecnico.surespace.verifier.manager.VerifierPropertyManager {
          + VerifierPropertyManager()
          + beforeLoading()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierKeyStoreManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.KeyStoreManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierKeyStoreManager o-- pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager : manager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierLogManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.LogManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager .up.|> pt.ulisboa.tecnico.surespace.common.manager.GlobalManagerInterface
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.common.manager.EntityManager : entityManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.verifier.manager.VerifierKeyStoreManager : keyStoreManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.verifier.manager.VerifierLogManager : logManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.common.manager.NonceManager : nonceManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.common.domain.Entity : orchestrator
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.orchestrator.client.OrchestratorClient : orchestratorClient
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierManager o-- pt.ulisboa.tecnico.surespace.verifier.manager.VerifierPropertyManager : propertyManager
  pt.ulisboa.tecnico.surespace.verifier.manager.VerifierPropertyManager -up-|> pt.ulisboa.tecnico.surespace.common.manager.PropertyManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
