@startuml

title __DOMAIN's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator {
          {static} - SCANNER : Scanner
          - server : Server
          + Orchestrator()
          + close()
          + openMenu()
          + proveLocation()
          + requestAuthorization()
          + requestProofInformation()
          + start()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator.HandleProof {
          + HandleProof()
          + onComplete()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase {
          - entries : HashMap<String, DatabaseEntry>
          + addEntry()
          + getEntry()
          + hasEntry()
          + listEntries()
          + removeEntry()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.orchestrator {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase.DatabaseEntry {
          {static} - serialVersionUID : long
          - services : LinkedHashSet<AdaptationServiceView>
          - signals : LinkedHashSet<Signal>
          + addSignals()
          + clone()
          + equals()
          + getServices()
          + getSignals()
          + getSignedAuth()
          + hashCode()
          + setServices()
          + setSignedAuth()
          + toString()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator o-- pt.ulisboa.tecnico.surespace.orchestrator.manager.OrchestratorManager : manager
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator o-- pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase : database
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator o-- pt.ulisboa.tecnico.surespace.ds2os.service.OrchestrationService : orchestrationService
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator +-down- pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator.HandleProof
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator.HandleProof .up.|> pt.ulisboa.tecnico.surespace.common.async.AsyncListener
  pt.ulisboa.tecnico.surespace.orchestrator.domain.Orchestrator.HandleProof o-- pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase.DatabaseEntry : entry
  pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase +-down- pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase.DatabaseEntry
  pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase.DatabaseEntry -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.orchestrator.domain.OrchestratorDatabase.DatabaseEntry o-- pt.ulisboa.tecnico.surespace.common.message.SignedRequestAuthorizationResponse : signedAuth


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
