@startuml

title __DEVICE's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace device {
      class pt.ulisboa.tecnico.surespace.arduino.device.LightBeacon {
          {static} - COMMAND : String
          - isOn : boolean
          - timer : Timer
          + LightBeacon()
          + isOn()
          + start()
          + stop()
          - changeIntensity()
          - turnOff()
          - turnOn()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace device {
      class pt.ulisboa.tecnico.surespace.arduino.device.LightWitness {
          + LightWitness()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace device {
      abstract class pt.ulisboa.tecnico.surespace.arduino.device.SensorWitness {
          - listenerId : long
          + SensorWitness()
          + start()
          + stop()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace device {
      class pt.ulisboa.tecnico.surespace.arduino.device.SoundBeacon {
          {static} + VOLUME_HIG : int
          {static} + VOLUME_LOW : int
          {static} + VOLUME_MAX : int
          {static} + VOLUME_MED : int
          {static} + VOLUME_MIN : int
          {static} - COMMAND : String
          {static} - EXECUTOR : ExecutorService
          {static} - VOLUME_TIMEOUT : int
          - currentVolume : int
          + SoundBeacon()
          + close()
          + nextSong()
          + pauseSong()
          + playSong()
          + previousSong()
          + resumeSong()
          + setVolume()
          + stop()
          - setEffectiveVolume()
          - setVolumeAndWait()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.arduino {
    namespace device {
      class pt.ulisboa.tecnico.surespace.arduino.device.SoundWitness {
          + SoundWitness()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.arduino.device.LightBeacon -up-|> pt.ulisboa.tecnico.surespace.arduino.pin.DigitalArduinoPin
  pt.ulisboa.tecnico.surespace.arduino.device.LightWitness -up-|> pt.ulisboa.tecnico.surespace.arduino.device.SensorWitness
  pt.ulisboa.tecnico.surespace.arduino.device.SensorWitness -up-|> pt.ulisboa.tecnico.surespace.arduino.pin.AnalogArduinoPin
  pt.ulisboa.tecnico.surespace.arduino.device.SoundBeacon -up-|> pt.ulisboa.tecnico.surespace.arduino.pin.DigitalArduinoPin
  pt.ulisboa.tecnico.surespace.arduino.device.SoundWitness -up-|> pt.ulisboa.tecnico.surespace.arduino.device.SensorWitness


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
