@startuml

title __ABSTRACT-SERVICE's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    abstract class pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.LockHandler {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    abstract class pt.ulisboa.tecnico.surespace.ds2os.service.Service {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    class pt.ulisboa.tecnico.surespace.ds2os.service.ServiceInitializer {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.SubscriberHandler {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    interface pt.ulisboa.tecnico.surespace.ds2os.service.VirtualNodeHandler {
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      abstract class pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace util {
      abstract class pt.ulisboa.tecnico.surespace.ds2os.service.util.ConstantPool {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace view {
      abstract class pt.ulisboa.tecnico.surespace.ds2os.service.view.ServiceView {
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace view {
      class pt.ulisboa.tecnico.surespace.ds2os.service.view.TypeSearchServiceView {
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.Service
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : beaconIsOn
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentCountNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentCurrentNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : fragmentLengthNode
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode : isLocked
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode : isStarted
  pt.ulisboa.tecnico.surespace.ds2os.service.AdaptationService o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : seedNode
  pt.ulisboa.tecnico.surespace.ds2os.service.Service .up.|> java.lang.AutoCloseable
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : agentRoot
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : knowledgeRoot
  pt.ulisboa.tecnico.surespace.ds2os.service.Service o-- pt.ulisboa.tecnico.surespace.ds2os.service.view.TypeSearchServiceView : searchService
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode .up.|> java.io.Serializable
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode .up.|> java.lang.Comparable
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode.NodeValue : value
  pt.ulisboa.tecnico.surespace.ds2os.service.view.ServiceView o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode : service
  pt.ulisboa.tecnico.surespace.ds2os.service.view.TypeSearchServiceView -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.view.ServiceView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
