@startuml

title __SIGNAL's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.common.signal {
    class pt.ulisboa.tecnico.surespace.common.signal.Fragment {
        - identifier : int
        - readings : HashMap<Pair<Device, Property>, LinkedList<Pair<Long, String>>>
        {static} - serialVersionUID : long
        + Fragment()
        + addReading()
        + clone()
        + equals()
        + getIdentifier()
        + getReadings()
        + hashCode()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.signal {
    class pt.ulisboa.tecnico.surespace.common.signal.Reading {
        {static} - serialVersionUID : long
        - time : long
        - value : String
        + Reading()
        + clone()
        + equals()
        + getDevice()
        + getProperty()
        + getTime()
        + getValue()
        + hashCode()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.signal {
    class pt.ulisboa.tecnico.surespace.common.signal.Signal {
        - fragments : LinkedList<Fragment>
        {static} - serialVersionUID : long
        + Signal()
        + addFragment()
        + clone()
        + equals()
        + getBeacon()
        + getFragments()
        + hashCode()
        + toString()
    }
  }
  

  pt.ulisboa.tecnico.surespace.common.signal.Fragment -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.signal.Reading -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.signal.Reading o-- pt.ulisboa.tecnico.surespace.common.proof.Device : device
  pt.ulisboa.tecnico.surespace.common.signal.Reading o-- pt.ulisboa.tecnico.surespace.common.signal.property.Property : property
  pt.ulisboa.tecnico.surespace.common.signal.Signal -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.signal.Signal o-- pt.ulisboa.tecnico.surespace.common.proof.Beacon : beacon


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
