@startuml

title __AUDIO's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace audio {
      class pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing {
          - period : int
          - proofLength : int
          - timer : Timer
          + init()
          + start()
          + stop()
          - cancelTimer()
          - getFilenameFromSongId()
          - getFramesPerSample()
          - getFramesTotal()
          - getWavFromResource()
          - reset()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace audio {
      class pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing.AudioProcessingTask {
          - framesPerPeriod : int
          - framesRead : long
          - framesTotal : long
          - listener : AsyncListener<Double, BroadException>
          + AudioProcessingTask()
          + run()
          - calculateAverage()
          - getFramesToRead()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace audio {
      class pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile {
          {static} - BUFFER_SIZE : int
          {static} - DATA_CHUNK_ID : int
          {static} - FMT_CHUNK_ID : int
          {static} - RIFF_CHUNK_ID : int
          {static} - RIFF_TYPE_ID : int
          - blockAlign : int
          - buffer : byte[]
          - bufferPointer : int
          - bytesPerSample : int
          - bytesRead : int
          - file : File
          - floatOffset : double
          - floatScale : double
          - frameCounter : long
          - iStream : FileInputStream
          - numChannels : int
          - numFrames : long
          - oStream : FileOutputStream
          - sampleRate : long
          - validBits : int
          - wordAlignAdjust : boolean
          + close()
          + getSampleRate()
          {static} + openWavFile()
          + readFrames()
          + readFrames()
          - WavFile()
          {static} - getLE()
          - readSample()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace audio {
      enum IOState {
        CLOSED
        READING
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing o-- pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile : wavFile
  pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing +-down- pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing.AudioProcessingTask
  pt.ulisboa.tecnico.surespace.ds2os.service.audio.AudioProcessing.AudioProcessingTask -up-|> java.util.TimerTask
  pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile o-- pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile.IOState : ioState
  pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile +-down- pt.ulisboa.tecnico.surespace.ds2os.service.audio.WavFile.IOState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
