@startuml

title __PROOF's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.common.proof {
    class pt.ulisboa.tecnico.surespace.common.proof.Beacon {
        {static} - serialVersionUID : long
        + Beacon()
        + clone()
        + getType()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.proof {
    abstract class pt.ulisboa.tecnico.surespace.common.proof.Device {
        # identifier : String
        # typedIdentifier : String
        {static} - serialVersionUID : long
        + Device()
        + equals()
        + getIdentifier()
        {abstract} + getType()
        + getTypedIdentifier()
        + hashCode()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.proof {
    class pt.ulisboa.tecnico.surespace.common.proof.LocationProof {
        {static} - serialVersionUID : long
        - signals : LinkedList<Signal>
        + LocationProof()
        + addSignal()
        + clone()
        + equals()
        + getAuthorization()
        + getSignals()
        + hashCode()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.proof {
    class pt.ulisboa.tecnico.surespace.common.proof.LocationProofProperties {
        - fragmentCount : int
        - fragmentLength : int
        - identifier : String
        - seed : long
        {static} - serialVersionUID : long
        + clone()
        + equals()
        + getFragmentCount()
        + getFragmentLength()
        + getIdentifier()
        + getSeed()
        + hashCode()
        + setFragmentCount()
        + setFragmentLength()
        + setIdentifier()
        + setSeed()
        + toString()
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.common.proof {
    class pt.ulisboa.tecnico.surespace.common.proof.Witness {
        {static} - serialVersionUID : long
        + Witness()
        + Witness()
        + clone()
        + getType()
    }
  }
  

  pt.ulisboa.tecnico.surespace.common.proof.Beacon -up-|> pt.ulisboa.tecnico.surespace.common.proof.Device
  pt.ulisboa.tecnico.surespace.common.proof.Device -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.proof.LocationProof -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.proof.LocationProof o-- pt.ulisboa.tecnico.surespace.common.message.SignedRequestAuthorizationResponse : authorization
  pt.ulisboa.tecnico.surespace.common.proof.LocationProofProperties -up-|> pt.ulisboa.tecnico.surespace.common.domain.Object
  pt.ulisboa.tecnico.surespace.common.proof.Witness -up-|> pt.ulisboa.tecnico.surespace.common.proof.Device


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
