@startuml

title __DOMAIN's Class Diagram__\n

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      abstract class pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode {
          {static} # LOGGER : Logger
          # address : String
          # connector : ServiceConnector
          {static} - serialVersionUID : long
          - subscribed : boolean
          + AbstractNode()
          + AbstractNode()
          + child()
          {static} + composeAddress()
          + equals()
          {static} + fixAddress()
          + getAddress()
          + getConnector()
          + getStream()
          + getValue()
          + hashCode()
          + isSubscribed()
          + lock()
          + parent()
          + setStream()
          {abstract} + setValue()
          + setValue()
          + setValue()
          + setValue()
          + setValue()
          + setValue()
          + setValue()
          {static} + splitAddress()
          + subscribe()
          + toString()
          + unsubscribe()
          # createLeaf()
          {abstract} # generateNode()
          {abstract} # get()
          - commit()
          - rollback()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode.NodeValue {
          - defaultValue : String
          - value : VslNode
          + NodeValue()
          + asBoolean()
          + asDouble()
          + asFloat()
          + asInteger()
          + asLong()
          + asString()
          + asVslNode()
          + withDefaultValue()
          - getDefaultValue()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode {
          {static} - MAX_RETRIES : int
          {static} - TIMEOUT : int
          {static} - serialVersionUID : long
          + RegularNode()
          + RegularNode()
          + compareTo()
          + setValue()
          # generateNode()
          # get()
          - get()
      }
    }
  }
  

  namespace pt.ulisboa.tecnico.surespace.ds2os.service {
    namespace domain {
      class pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode {
          {static} - serialVersionUID : long
          + VirtualNode()
          + VirtualNode()
          + register()
          + setValue()
          + unregister()
          # generateNode()
          # get()
          - newInvalidOperationException()
      }
    }
  }
  

  pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode .up.|> java.io.Serializable
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode +-down- pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode.NodeValue
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode .up.|> java.lang.Comparable
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.RegularNode -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode -up-|> pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode
  pt.ulisboa.tecnico.surespace.ds2os.service.domain.VirtualNode o-- pt.ulisboa.tecnico.surespace.ds2os.service.domain.AbstractNode.NodeValue : value


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
